name: Update Data JSON

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies (if needed)
      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No dependencies required"

      # Step 4: Run the Python script
      - name: Generate JSON files
        run: python gallery/assets/generate_json.py

      # Step 5: Commit and push the changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gallery/assets/img/photos/data.json gallery/assets/img/gaul/data.json
          git commit -m "Update data.json files"
          git push origin main
